application: udacity-multiuser-blog-2112
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /js/
  static_dir: static/js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: latest

- name: lxml
  version: "2.3"

